const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getAppPath: () => ipcRenderer.invoke('get-app-path'),
  readFile: (path) => ipcRenderer.invoke('read-file', path),
  writeFile: (path, data) => ipcRenderer.invoke('write-file', path, data),
  openFileDialog: (filters) => ipcRenderer.invoke('open-file-dialog', filters),
  saveFileDialog: (defaultName, filters) => ipcRenderer.invoke('save-file-dialog', defaultName, filters),
  readDir: (dirPath) => ipcRenderer.invoke('read-dir', dirPath),
  deleteFile: (filePath) => ipcRenderer.invoke('delete-file', filePath),
  copyFile: (src, dest) => ipcRenderer.invoke('copy-file', src, dest),
  unzipFile: (zipPath, destDir) => ipcRenderer.invoke('unzip-file', zipPath, destDir),
  zipDir: (dirPath, zipPath) => ipcRenderer.invoke('zip-dir', dirPath, zipPath),
  getResourcePath: (relPath) => ipcRenderer.invoke('get-resource-path', relPath),
  findQgpshFiles: () => ipcRenderer.invoke('find-qgpsh-files'),
  quickLoadQgpsh: (path) => ipcRenderer.invoke('quick-load-qgpsh', path),
  openDirectoryDialog: () => ipcRenderer.invoke('open-directory-dialog'),
  usersGet: () => ipcRenderer.invoke('users-get'),
  usersSave: (users) => ipcRenderer.invoke('users-save', users),
  userLogin: (login, password) => ipcRenderer.invoke('user-login', login, password),
  userRegister: (data) => ipcRenderer.invoke('user-register', data),
  userBalance: (username) => ipcRenderer.invoke('user-balance', username),
  shopBuy: (username, itemId, price) => ipcRenderer.invoke('shop-buy', username, itemId, price),
  adminAddBalance: (username, amount) => ipcRenderer.invoke('admin-add-balance', username, amount),
  adminSetPassword: (username, newPassword) => ipcRenderer.invoke('admin-set-password', username, newPassword),
  ghCheckUpdate: () => ipcRenderer.invoke('gh-check-update'),
  ghUpdateNow: () => ipcRenderer.invoke('gh-update-now'),
  ghApplyUpdate: () => ipcRenderer.invoke('gh-apply-update'),
  ghStagedUpdate: () => ipcRenderer.invoke('gh-staged-update'),
  usersSync: () => ipcRenderer.invoke('users-sync'),
  on: (channel, callback) => ipcRenderer.on(channel, (event, ...args) => callback(...args)),
  removeAllListeners: (channel) => ipcRenderer.removeAllListeners(channel),
});
